### ISSUE TITLE
Check if BT, Ros Bridge Server (Weblink to connect to website), Robot_Localization (Localization and orientation), SLAM_TOOLBOX (2D Mapping) , OCTOMAP (3D)

### ISSUE THREAD

**Issue by ZefraSK** [Weber-State-Submarine-Project/Submarine#39]
DONE: If we see that the libraries will work with Jazzy.

 If does not work with Jazzy.
- [ ] Ben will test simulation with Jazzy
- [ ] Docker setup for Humble

**Comment by Ben1219925** [comment]
Since Jazzy is only supported on Ubuntu 24.04 I am unable to test/adjust the simulation on the Linux laptop without upgrading to 24.04 which would likely require wiping the computer and restarting with the new OS. Which is certainly not ideal. Instead I'm planning on setting up a VirtualBox on my own PC to test with.

**Comment by ZefraSK** [comment]
Currently everything builds with Jazzy. Apparently Robot localization is having issues. Ben is currently working on it. Simulation is not working as well due to jazzy. Will try to use Gazebo Harmonic.

**Comment by ZefraSK** [comment]
Ben has it working with jazzy already
