### ISSUE TITLE
Research if we can choose IP for Pi5 Linux

### ISSUE THREAD

**Issue by ZefraSK** [Weber-State-Submarine-Project/Submarine#43]
DONE: When we can confirm if possible to change IP

**Comment by Ben1219925** [comment]
We can hard code an IP address on Linux, but it probably isn't worth it since the automatic IP address is easy to get and hard coding IP addresses isn't always reliable unless you know for sure that that address isn't used by any other devices and all of the hard coded masks DNS etc. match with the network requirements.
